#!/usr/bin/env bash

function setup()
{
    echo '>>> Setting up...'

    source .env
    export DOCKER_NETWORK \
        PUBLIC_URL
}

function run()
{
    echo '>>> Running...'

    docker run \
        -e VIRTUAL_HOST=$PUBLIC_URL \
        -e CERT_NAME=shared \
        -v $PWD/dist:/usr/share/nginx/html \
        -v $PWD/site.conf:/etc/nginx/conf.d/site.conf \
        --name ${PWD##*/} \
        --network $DOCKER_NETWORK \
        nginx:alpine
}

function cleanup()
{
    echo '>>> Cleaning up...'
    docker stop ${PWD##*/}

    docker rm ${PWD##*/}
    echo '>>> Cleanup done. Have a great day!'
}

cleanup
setup
run

trap cleanup EXIT SIGINT
